spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cachedemo?characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
server:
  port: 8080